
enum Submenu : std::uint32_t
{
	SubmenuSettingsHeader,
	SubmenuSettingsHeaderStaticBackground,
	SubmenuSettingsHeaderGradientBackground,
	SubmenuSettingsHeaderYTDBackground,
	SubmenuSettingsHeaderYTDList,
	SubmenuSettingsHeaderText,
	SubmenuSettingsSubmenuBar,
	SubmenuSettingsOption,
	SubmenuSettingsFooter,
	SubmenuSettingsDescription,
	SubmenuSettingsInput,
	SubmenuSettingsLanguage,
	SubmenuHome,
	SubmenuLocal,
	SubmenuNetwork,
	SubmenuVehicle,
	SubmenuSpawner,
	SubmenuVehAcrobatics,
	SubmenuVehBomber,
	SubmenuPlayerList,
	SubmenuNetowrk,
	SubmenuAllPlayer,
	SubmenuSessionWeather,
	SubmenuSelectedPlayer,
	SubmenuWeapon,
	SubmenuExplosive,
	SubmenuWepmod,
	SubmenuImpact,
	SubmenuTeleport,
	SubmenuRecovery,
	SubmenuESP,
	SubmenuMisc,
	SubmenuSettings,
	SubmenuInfo,
	SubmenuWorld,
	SubmenuWorldPeds,
	SubmenuWorldVehicles,
	SubmenuOfflineRecovery,
	SubmenuSelf,
	SubmenuCustomization,
	SubmenuExperimental,
	SubmenuTeleports,
	SubmenuPresetTeleports,
	SubmenuTeleportManager,
	SubmenuScripts,
	SubmenuExecutable,
	SubmenuSHV,

	// Network
	SubmenuProtections,
	SubmenuGameProtections,
	SubmenuStats,
	SubmenuScriptEProtex,
	SubmenuNetworkEProtex,
	SubmenuMerryWeather,
	SubmenuInfoSpoofer,
	SubmenuRemoteOptions,
	SubmenuGriefOptions,
	SubmenuDropOptions,
	SubmenuNiceOptions,
	SubmenuPVehicleOptions,
	SubmenuAttachmentOptions,

	// Vehicles
	SubmenuDLCVehicles,
	SubmenuFunVehicleOptions,
	SubmenuSpawnerSettings,
	SubmenuVehicleAesthetics,
	SubmenuVehicleHealth,
	SubmenuVehicleMovement,
	SubmenuVehicleWeapons,
	SubmenuVehicleLSC,
	SubmenuVehicleSuperCars,
	SubmenuVehicleMultipliers,

	// All Player
	SubmenuAllChatCmds,
	SubmenuAllRemotes,
	SubmenuAllSessionMods,
	SubmenuAllTeleports,
	SubmenuAllTimeMods,

	// Other Player
	SubmenuPlayerChatCmds,
	SubmenuPlayerDropItems,
	SubmenuPlayerGriefing,
	SubmenuPlayerTeleport,
	SubmenuPlayerWeapon,
	SubmenuPlayerVehicle,
	SubmenuPlayerBodyGuard,
	SubmenuWeaponInventory,
	SubmenuPlayerRemote,
	SubmenuPlayerBlame,
	SubmenuPlayerESP,
	SubmenuPlayerFriendly,
	SubmenuPlayerSpawnVehicle,
	SubmenuPlayerSpawner,
	SubmenuPlayerDLCVehicles,
	SubmenuPlayerExplosions,
	SubmenuPlayerAttachments,

	// Remotes
	SubmenuRemoteNotifications,
	SubmenuRemoteTeleports,

	// Weapons
	SubmenuWeaponAmmo,
	SubmenuWeaponMods,
	SubmenuKillSpoofer,

	// Recovery
	SubmenuATM,
	SubmenuMoney,
	SubmenuRank,
	SubmenuUnlocks,
	SubMenuStatSpoofer,
	SubmenuSpecialUnlocks,
	SubmenuCasinoUnlocks,
	SubmenuStatsEditor,

	// Teleport
	SubmenuTPBunkers,
	SubmenuTPHighPlaces,
	SubmenuTPIndoors,
	SubmenuTPIPLs,
	SubmenuTPLandmarks,
	SubmenuTPSafehouses,
	SubmenuTPUnderwater,

	//ASI
	SubmenuScripthook,

	//SPOTIFY
	SubmenuSpotify,

	SubmenuWardrobe,
	SubmenuModel,
};
